version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.1.0-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: quote_api
          RAILS_ENV: test
      - image: cimg/postgres:9.6.24
        environment:
          POSTGRES_USER: quote_api
          POSTGRES_DB: quote_test
          POSTGRES_PASSWORD: ""
      - image: redis
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Update Rubygems and Bundler
          command: |
            gem update --system
            gem install bundler

      - run:
          name: Update apt
          command: |
            sudo apt-get update

      - run:
          name: Download xvfb
          command: |
            sudo apt-get install xvfb

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      # Run rspec in parallel
      - run:
          name: Run rspec
          command: |
            xvfb-run -a bundle exec rspec --out test_results/rspec.xml \
                              --format progress

      # Save test results for timing analysis
      - store_test_results:
          path: test_results